### ISSUE TITLE
Technicolor is not listed

### ISSUE THREAD

**Issue by PeterPedro** [kristate/krackinfo#188]
Why are Technicolor modem/router not listed?

**Comment by zeadope-zz** [comment]
Modems / routers are not affected (unless they have a mode to act as a Wi-Fi client (-bridge). Fixes have to be made at the client devices.

**Comment by eaglerainbow** [comment]
> Why are Technicolor modem/router not listed?

I'd rather say: because nobody added them yet.

> Modems / routers are not affected [...]

Well, given that they apparently also sell [IoT devices](http://www.technicolor.com/en/solutions-services/connected-home/iot-devices) and [WDS-enabled devices](http://www.technicolor.com/en/solutions-services/connected-home/broadband-devices/accessories/mwa1221), at least they *could* be affected. Thus, an official statement is at least desirable.

**Comment by zeadope-zz** [comment]
Makes sense to add them if they sell wireless clients.
